settings = {'animrange': ['1', '24', '1'],
			'animtype': 0,
			'asnurmbs': True,
			'colornaming': 1,
            'compress': 0,
			'curvgrp_layer': [False, '', 'LAYER_'],
			'curvgrp_obj': [False, '', 'OBJ_'],
			'curvgrp_par': [False, '', 'PAR_'],
			'expHi': True,
			'expanim': False,
			'expcolor': False,
			'expcrease': False,
			'expcurve': True,
			'expcurveglobEnable': True,
			'expcurveglobname': 'CURV_',
			'expgeogrp_layer': [False, '', 'LAYER_'],
			'expgeogrp_mtl': [False, '', 'MTL_'],
			'expgeogrp_obj': [False, '', 'OBJ_'],
			'expgeogrp_parent': [False, '', 'PRNT_'],
			'expgeogrp_shp': [False, '', 'SHAPE_'],
			'exportgeo': True,
			'exportpath': '',
			'exppartattrib': [False, ''],
			'exppartgrp_emit': [False, '', 'EMITTER_'],
			'exppartgrp_shape': [False, '', 'OBJ_'],
			'expparticle': True,
			'expparticlglobEnable': True,
			'expparticlglobname': 'PART_',
			'exppiv': False,
			'exppivattrib': [False, ''],
			'exppivfilter': '',
			'exppivgrp_obj': [False, '', 'OBJ_'],
			'exppivgrp_parent': [False, '', 'PAR_'],
			'exppivgrp_shape': [False, '', 'INSTATCE_'],
			'exppivgrp_layer': [False, '', 'LAYER_'],
			'exppivorient': True,
			'exppivotglobEnable': True,
			'exppivotglobname': 'PIVOT_',
			'exppivscale': True,
			'exppivskipnoshape': True,
			'expuv': True,
			'expvertexnorm': False,
			'expvis': False,
			'fileExists': 1,
			'fileformat': 0,
			'geocustomattr': [False, ''],
			'geoglobalEnable': True,
			'geoglobalname': 'POLY_',
			'globalpos': True,
			'gzip': False,
			'scale': 0.01,
			'uvnaming': 1,
			'writefile': True,
            'curvcustomattrib': [0, {}],
			}

# Attribute presets for custom attributes tables
attrTableCurves_tbw = {
    'Arnold Width':['aiCurveWidth','width','1'],
    'Arnold Render Mode':['aiMode','','1'],
}
attrTablePart_tbw = {
    'rgbPP':['rgbPP', 'Cd', '0,0,0'],
    'radiusPP':['radiusPP', 'pscale', '1'],
    'opacityPP':['opacityPP', 'a', '1'],
    'lifespan':['lifespan', 'life', '0'],
    'velocity':['velocity', 'v', '0'],
    'age':['age', '', '0'],
    'particleId':['particleId', 'id', '0'],
    'emitterId':['emitterId', '', '0'],

}