# object name : settings slot
widgets = {
'rangeFrame_rb':'expanim',
'singleFrame_rb':'expanim',
'startFrame_spb':'animrange',
'endFrame_spb':'animrange',
'stepFrame_spb':'animrange',

'sequence_rb':'animtype',
'mdd_rb':'animtype',
'exportPath_le':'exportpath',
'formatGeo_rb':'fileformat',
'formatBgeo_rb':'fileformat',
'fileFormat_cbb':'fileformat',
'formatGzip_cb':'gzip',
'cacheOnly_cbb':'writefile',
'cacheFormat_cbb':'animtype',
'compress_cbb':'compress',
'worldPos_rb':'globalpos',
'localPos_rb':'globalpos',
'scale_le':'scale',

'writeFile_cb':'writefile',
'fileAsk_rb':'fileExists',
'fileOverride_rb':'fileExists',
'fileSkip_rb':'fileExists',
'fileRename_rb':'fileExists',
'expVis_cb':'expvis',
'expHierarchy_cb':'expHi',

'exportGeo_cb':'exportgeo',
'expGeoGlobalGroupName_le':'geoglobalname',
'exportUv_cb':'expuv',
'exportVerNorm_cb':'expvertexnorm',
'exportVertexColor_cb':'expcolor',
'exportCrease_cb':'expcrease',
'customGeoAttr_le':'geocustomattr',
'customGeoAttr_cb':'geocustomattr',
'attrTablePoly_tbw':'geocustomattr',


'byMtl_cb':'expgeogrp_mtl',
'byMtl_le':'expgeogrp_mtl',
'byMtlPref_le':'expgeogrp_mtl',
'byPar_cb':'expgeogrp_parent',
'byPar_le':'expgeogrp_parent',
'byParPref_le':'expgeogrp_parent',
'byObj_cb':'expgeogrp_obj',
'byObj_le':'expgeogrp_obj',
'byObjPref_le':'expgeogrp_obj',
'byShape_cb':'expgeogrp_shp',
'byShape_le':'expgeogrp_shp',
'bySpahePref_le':'expgeogrp_shp',
'displayer_cb':'expgeogrp_layer',
'byLayer_le':'expgeogrp_layer',
'byLayerPref_le':'expgeogrp_layer',

'exportCurv_cb':'expcurve',
'curvToNURBS_rb':'asnurmbs',
'curvToPoly_rb':'asnurmbs',
'customCrvAttr_cbx':'curvcustomattrib',
'attrTableCurves_tbw':'curvcustomattrib',
'expCurvesGlobalGroupName_le':'expcurveglobname',
'byCrvObj_cb':'curvgrp_obj',
'byCurvObj_le':'curvgrp_obj',
'byCurvObjPref_le':'curvgrp_obj',
'byCrvPar_cb':'curvgrp_par',
'byCurvPar_le':'curvgrp_par',
'byCurvParPref_le':'curvgrp_par',
'curvDisplayer_cb':'curvgrp_layer',
'byCurvLayer_le':'curvgrp_layer',
'byCurvLayerPref_le':'curvgrp_layer',

'exportparticles_cb':'expparticle',
'expParticlesGlobalGroupName_le':'expparticlglobname',
'byPartObj_cb':'exppartgrp_shape',
'byPartObj_le':'exppartgrp_shape',
'byPartObjPref_le':'exppartgrp_shape',
'byEmit_cb':'exppartgrp_emit',
'byEmit_le':'exppartgrp_emit',
'byEmitPref_le':'exppartgrp_emit',
'customPartAttr_cb':'exppartattrib',
'customAttr_le':'exppartattrib',
'attrTablePart_tbw':'exppartattrib',

'pivot_cb':'exppiv',
'expPivotsGlobalGroupName_le':'exppivotglobname',
'expPivotObj_cb':'exppivgrp_obj',
'expPivotObj_le':'exppivgrp_obj',
'expPivotObjPref_le':'exppivgrp_obj',
'expPivotShape_cb':'exppivgrp_shape',
'expPivotShape_le':'exppivgrp_shape',
'expPivotShapePref_le':'exppivgrp_shape',
'expPivotParent_cb':'exppivgrp_parent',
'expPivotParent_le':'exppivgrp_parent',
'expPivotParentPref_le':'exppivgrp_parent',
'expPivotLayer_cb':'exppivgrp_layer',
'expPivotlayer_le':'exppivgrp_layer',
'expPivotLayerPref_le':'exppivgrp_layer',

'exportOrient_cb':'exppivorient',
'scale_cb':'exppivscale',
'customPivotAttr_le':'exppivattrib',
'customPivotAttr_cb':'exppivattrib',
'attrTablePiv_tbw':'exppivattrib',
'pivotFilter_le':'exppivfilter',
'pivSkipTransform_cb':'exppivskipnoshape',

'uvExportNaming':'uvnaming',
'colorExportNaming':'colornaming',
'polyGroupEnable_cb':'geoglobalEnable',
'curveGroupEnable_cb':'expcurveglobEnable',
'partGroupEnable_cb':'expparticlglobEnable',
'pivotGroupEnable_cb':'exppivotglobEnable',

'cdSetName1_act':'colornaming',
'cdSetName2_act':'colornaming',
'cdSetName3_act':'colornaming',
'uvSetName1_act':'uvnaming',
'uvSetName2_act':'uvnaming',
'uvSetName3_act':'uvnaming',

}